version: '2.1'

services:  
  ci-build:
    image: microsoft/aspnetcore-build:1.1.2-nanoserver
    container_name: build

    volumes:
     - U:\russell\projects\docker_netcore_windows\compose\src:c:\src

    command: dotnet restore c:\\src\\app.sln -v diagnostic
    ports:
      - "5000:5000"



networks:
  default:
    external: 
      name: nat
          
      